Repository UMC8-TeumTeum/BE, pull requests merged in 2025-07, with the labels that each got.

#11 Feat: 인증&온보딩 API Swagger 문서화
  .github/workflows/CI.yml
  src/main/java/umc/teumteum/server/domain/auth/controller/AuthController.java
  src/main/java/umc/teumteum/server/domain/auth/dto/AuthRequestDTO.java
  src/main/java/umc/teumteum/server/domain/auth/dto/AuthResponseDTO.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthService.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/controller/UserController.java
  src/main/java/umc/teumteum/server/domain/user/converter/UserConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/UserRequestDTO.java
  src/main/java/umc/teumteum/server/domain/user/dto/UserResponseDTO.java
  src/main/java/umc/teumteum/server/domain/user/repository/UserRepository.java
  src/main/java/umc/teumteum/server/domain/user/service/UserService.java
  src/main/java/umc/teumteum/server/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature, 📃 Docs

#12 Feat: 친구, 틈 API Swagger 문서
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FavoriteRequestDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FavoriteResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FollowResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FriendMutualResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/entity/Friend.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendErrorStatus.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/friend/repository/FriendRepository.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/availability/AvailableTimeRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/availability/AvailableTimeResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/common/ParticipantDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/common/TimeSlot.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumDetailResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumExitResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/shared/SharedTeumResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumReceivedResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumRequestDetailResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResendRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResendResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResponseStatus.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumStatusUpdateRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumStatusUpdateResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/entity/TeumRequest.java
  src/main/java/umc/teumteum/server/domain/teum/entity/TeumResponse.java
  src/main/java/umc/teumteum/server/domain/teum/repository/TeumRepository.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature, 📃 Docs

#15 Feat: 친구 기능 API Controller 작성
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FollowerUserResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FollowingUserResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/controller/UserController.java
  src/main/java/umc/teumteum/server/domain/user/dto/PublicTodoResponseDto.java
  src/main/java/umc/teumteum/server/domain/user/service/UserService.java
  src/main/java/umc/teumteum/server/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature, 📃 Docs

#25 Feat: 추가 API Controller 구현
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FriendProfileResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/dto/shared/SharedTeumListResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumRequestResponseDto.java
Labels: ✨ Feature, 📃 Docs

#32 Fix : 브랜치 생성 직후 CI 실행되지 않도록 조건 추가
  .github/workflows/CI.yml
Labels: 🌏 Deploy, ⚙ Setting

#33 Feat: 틈 요청 목록 조회 API 구현
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/common/ParticipantDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumReceivedResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/repository/TeumResponseRepository.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#37 Feat: 틈 재요청 API 구현
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResendRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/entity/TeumResponse.java
  src/main/java/umc/teumteum/server/domain/teum/entity/enums/ResponseStatus.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumErrorStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#40 Feat: 틈 요청 읽기 API 구현
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumRequestDetailResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#46 Feat: 친구 프로필 조회 API 구현
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendErrorStatus.java
  src/main/java/umc/teumteum/server/domain/friend/repository/FriendRepository.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/global/config/S3Config.java
  src/main/java/umc/teumteum/server/global/util/S3Util.java
Labels: ✨ Feature

#43 Feat: 닉네임으로 사용자 조회 API 구현
  build.gradle
  src/main/java/umc/teumteum/server/domain/user/controller/UserController.java
  src/main/java/umc/teumteum/server/domain/user/converter/UserConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/UserSearchResponseDto.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/repository/UserRepository.java
  src/main/java/umc/teumteum/server/domain/user/service/UserService.java
  src/main/java/umc/teumteum/server/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature

#48 Feat: 친구의 빈틈 시간 조회 API 구현
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
Labels: ✨ Feature

#44 Feat: 투두 CRUD API 구현
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/TodoIdResponseDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/TodoInfoResponseDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/TodoRequestDTO.java
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/home/entity/mapping/TeumMate.java
  src/main/java/umc/teumteum/server/domain/home/exception/HomeException.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleReminderRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
  src/main/java/umc/teumteum/server/domain/teum/entity/TeumRequest.java
  src/main/java/umc/teumteum/server/domain/teum/entity/enums/ResponseStatus.java
  src/main/java/umc/teumteum/server/domain/user/entity/User.java
Labels: ✨ Feature

#53 Feat: 틈 응답 상태 변경 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumResponseStatus.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumStatusUpdateRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/teum/TeumStatusUpdateResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumErrorStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#56 Feat: 시간표(공통 가능 시간대) 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/availability/AvailableTimeRequestDto.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/entity/enums/Weekday.java
Labels: ✨ Feature

#57 Feat: 위시 관련 기능 API 구현
  src/main/java/umc/teumteum/server/domain/home/controller/WishController.java
  src/main/java/umc/teumteum/server/domain/home/converter/WishConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/WishDeleteRequestDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/WishInfoResponseDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/WishRequestDTO.java
  src/main/java/umc/teumteum/server/domain/home/entity/Wish.java
  src/main/java/umc/teumteum/server/domain/home/entity/enums/EstimatedDuration.java
  src/main/java/umc/teumteum/server/domain/home/entity/mapping/WishCategory.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/CategoryRepository.java
  src/main/java/umc/teumteum/server/domain/home/repository/WishRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: ✨ Feature

#62 Feat: 약속된 틈 날짜 리스트 반환 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#74 Feat : 닉네임 & 분야/직종 등록 API 구현
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/dto/UserRequestDTO.java
  src/main/java/umc/teumteum/server/domain/user/entity/User.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/repository/UserRepository.java
  src/main/java/umc/teumteum/server/domain/user/service/UserService.java
  src/main/java/umc/teumteum/server/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature

#76 Feat: 약속된 틈 상세조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumDetailResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumErrorStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
  src/main/java/umc/teumteum/server/global/util/S3Util.java
Labels: ✨ Feature

#81 Feat: 약속된 틈 취소 API 구현
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumCancelResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumExitResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#83 Feat : 위시 투두 등록 기능 구현
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/controller/WishController.java
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/WishAssignRequestDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodayScheduleResponseDTO.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodyTeumResponseDTO.java
  src/main/java/umc/teumteum/server/domain/home/entity/enums/ScheduleType.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/repository/RoutineRepository.java
  src/main/java/umc/teumteum/server/domain/user/repository/UserRepository.java
  src/main/java/umc/teumteum/server/global/scheduler/ScheduleGeneratorScheduler.java
Labels: ✨ Feature

#87 Feat: 특정 날짜의 약속된 틈 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/schedule/ScheduledTeumResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#91 Feat : 반복일정 스케줄 등록 스케줄러 수정
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/entity/TeumResponse.java
  src/main/java/umc/teumteum/server/domain/user/entity/RemindAlarm.java
  src/main/java/umc/teumteum/server/global/scheduler/ScheduleGeneratorScheduler.java
Labels: ✨ Feature

#93 Fix : 위시 등록 중복 검증 로직 제거
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: 🐞 BugFix

#95 Feat: 수면 패턴 등록 API 구현
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/converter/AgreementConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/main/java/umc/teumteum/server/domain/user/entity/User.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingService.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/service/UserService.java
  src/main/java/umc/teumteum/server/domain/user/service/UserServiceImpl.java
Labels: ✨ Feature

#97 Feat : 위시 카테고리 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/controller/WishController.java
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/converter/WishConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/TodoRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/WishAssignRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/WishDeleteRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/WishRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/CategoryResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodayScheduleResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodoIdResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodoInfoResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/WishInfoResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/WishlistResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: ✨ Feature

#101 Feat: 지금까지 채운 빈틈 조회 API 구현
  src/main/java/umc/teumteum/server/ServerApplication.java
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/HomeResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/controller/UserController.java
Labels: ✨ Feature, 🙋‍♂️ Question

#105 Feat: 반복일정 등록 API 구현
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/converter/RoutineConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/main/java/umc/teumteum/server/domain/user/exception/OnboardingHandler.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/repository/RoutineRepository.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingService.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingServiceImpl.java
  src/main/java/umc/teumteum/server/global/dto/TimeRange.java
  src/main/java/umc/teumteum/server/global/util/TimeUtil.java
  src/test/java/umc/teumteum/server/unit/user/service/OnboardingServiceTest.java
Labels: ✨ Feature, ✅ Test

#109 Refactor: CD 파이프라인 정비 및 스케줄러 코드 최적화, 테스트 코드 추가
  .github/workflows/CD.yml
  build.gradle
  src/main/java/umc/teumteum/server/domain/fcm/repository/FcmTokenRepository.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/user/entity/User.java
  src/main/java/umc/teumteum/server/global/scheduler/DailyTodoReminerScheduler.java
  src/test/java/umc/teumteum/server/unit/global/scheduler/DailyTodoReminderSchedulerTest.java
Labels: 🌏 Deploy, ✅ Test, 🔨 Refactor

#112 Feat: 프로필 이미지 업로드용 프리사인드 URL 발급 API 구현
  src/main/java/umc/teumteum/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/converter/OnboardingConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingResponseDto.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingService.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingServiceImpl.java
  src/main/java/umc/teumteum/server/global/util/S3Util.java
Labels: ✨ Feature

#113 Fix: 친구의 빈틈 시간 조회 API 조건 추가
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FriendTeumTimeResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
Labels: 🐞 BugFix, ✨ Feature

#116 Feat: 프로필 이미지 등록 API 구현
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingService.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingServiceImpl.java
Labels: ✨ Feature
