Repository UMC8-TeumTeum/BE, pull requests merged in 2025-08, with the labels that each got.

#125 Feat: 채움활동 위시리스트 불러오기 API 구현
  src/main/java/umc/teumteum/server/domain/home/controller/ActivityController.java
  src/main/java/umc/teumteum/server/domain/home/converter/WishConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/ActivityRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/ActivityResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/WishCategoryRepository.java
  src/main/java/umc/teumteum/server/domain/home/repository/WishRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/ActivityService.java
  src/main/java/umc/teumteum/server/domain/home/service/ActivityServiceImpl.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/test/java/umc/teumteum/server/unit/home/service/ActivityServiceTest.java
Labels: ✨ Feature, ✅ Test

#130 Feat: 틈 요청 날짜 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/teum/repository/TeumRequestRepository.java
  src/main/java/umc/teumteum/server/domain/teum/repository/TeumResponseRepository.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#136 Feat: 리마인드 알림 등록 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/user/controller/OnboardingController.java
  src/main/java/umc/teumteum/server/domain/user/converter/AgreementConverter.java
  src/main/java/umc/teumteum/server/domain/user/converter/OnboardingConverter.java
  src/main/java/umc/teumteum/server/domain/user/converter/RoutineConverter.java
  src/main/java/umc/teumteum/server/domain/user/dto/OnboardingRequestDto.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserErrorStatus.java
  src/main/java/umc/teumteum/server/domain/user/exception/status/UserSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingService.java
  src/main/java/umc/teumteum/server/domain/user/service/OnboardingServiceImpl.java
Labels: ✨ Feature

#138 Feat: 팔로우/언팔로우하기 API 구현
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FollowResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/exception/FriendException.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendErrorStatus.java
  src/main/java/umc/teumteum/server/domain/friend/repository/FriendRepository.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
Labels: ✨ Feature

#142 Fix: 투두 자정 처리 & 충돌 검사
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/HomeResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodayScheduleResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/TodoInfoResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
  src/main/java/umc/teumteum/server/global/util/DateTimeSerializer.java
  src/main/java/umc/teumteum/server/global/util/TimeSerializer.java
  src/main/java/umc/teumteum/server/global/validator/ConflictValidator.java
Labels: 🐞 BugFix

#141 Feat: 서로의 빈틈을 함께한 시간 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/shared/SharedTeumResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/dto/shared/SharedTeumTimeResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumErrorStatus.java
  src/main/java/umc/teumteum/server/domain/teum/exception/status/TeumSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature, 🙋‍♂️ Question

#151 Feat: 즐겨찾기 설정/해제 API 구현
  src/main/java/umc/teumteum/server/domain/friend/controller/FriendController.java
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FavoriteRequestDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FavoriteResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FriendRequestDto.java
  src/main/java/umc/teumteum/server/domain/friend/dto/FriendResponseDto.java
  src/main/java/umc/teumteum/server/domain/friend/entity/Friend.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendErrorStatus.java
  src/main/java/umc/teumteum/server/domain/friend/exception/status/FriendSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendService.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
Labels: ✨ Feature

#159 Feat: 함께한 틈 목록 조회 API 구현
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/controller/TeumController.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/dto/shared/SharedTeumListResponseDto.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumService.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#155 Fix: 투두리스트 조회 hasAlarm 필드 변경
  src/main/java/umc/teumteum/server/domain/home/converter/ScheduleConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/HomeResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/home/entity/ScheduleReminder.java
  src/main/java/umc/teumteum/server/domain/home/entity/enums/AlarmStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleReminderRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
  src/main/java/umc/teumteum/server/global/scheduler/ScheduleGeneratorScheduler.java
Labels: 🐞 BugFix

#164 Feat: 토큰 재발급 API 구현 및 인증 흐름 개선
  src/main/java/umc/teumteum/server/domain/auth/controller/AuthController.java
  src/main/java/umc/teumteum/server/domain/auth/converter/AuthConverter.java
  src/main/java/umc/teumteum/server/domain/auth/dto/AuthRequestDTO.java
  src/main/java/umc/teumteum/server/domain/auth/dto/AuthResponseDTO.java
  src/main/java/umc/teumteum/server/domain/auth/exception/status/AuthErrorStatus.java
  src/main/java/umc/teumteum/server/domain/auth/exception/status/AuthSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthService.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/umc/teumteum/server/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/teumteum/server/global/config/RedisConfig.java
  src/main/java/umc/teumteum/server/global/config/SecurityConfig.java
  src/main/java/umc/teumteum/server/global/exception/TokenBlacklistException.java
  src/main/java/umc/teumteum/server/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/umc/teumteum/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/teumteum/server/global/jwt/JwtProvider.java
  src/main/java/umc/teumteum/server/global/monitoring/service/InfraRedisServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#171 Refactor: S3Util 사용 로직을 컨버터에서 서비스 계층으로 이동
  src/main/java/umc/teumteum/server/domain/friend/converter/FriendConverter.java
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/teum/converter/TeumConverter.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: 🔨 Refactor

#168 Feat : 리마인드 알림 온오프 기능 구현
  src/main/java/umc/teumteum/server/domain/home/controller/HomeController.java
  src/main/java/umc/teumteum/server/domain/home/controller/WishController.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/HomeRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/entity/ScheduleReminder.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleReminderRepository.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeService.java
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: ✨ Feature

#174 Refactor : 채움활동 ai 컨텐츠 추천 API 수정
  src/main/java/umc/teumteum/server/domain/home/ai/generator/AiWishGenerator.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/ActivityRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/entity/enums/LocationType.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/service/ActivityServiceImpl.java
Labels: 🔨 Refactor

#176 Feat: 로그아웃 API 구현
  src/main/java/umc/teumteum/server/domain/auth/controller/AuthController.java
  src/main/java/umc/teumteum/server/domain/auth/exception/status/AuthSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthService.java
  src/main/java/umc/teumteum/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/umc/teumteum/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/teumteum/server/global/jwt/JwtProvider.java
Labels: ✨ Feature

#180 Feat: 틈 시작 시간 경과 시 자동 완료 처리하는 스케줄러 추가
  src/main/java/umc/teumteum/server/domain/home/entity/Schedule.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/global/scheduler/TeumStatusScheduler.java
Labels: ✨ Feature

#184 Feat : AI 컨텐츠 투두 등록 API 구현
  src/main/java/umc/teumteum/server/domain/home/controller/ActivityController.java
  src/main/java/umc/teumteum/server/domain/home/converter/WishConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/request/ActivityRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/ActivityResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeErrorStatus.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/service/ActivityService.java
  src/main/java/umc/teumteum/server/domain/home/service/ActivityServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#190 Refactor: Graphics 엔티티 및 TeumMateStatus Enum 삭제
  src/main/java/umc/teumteum/server/domain/home/entity/enums/TeumMateStatus.java
  src/main/java/umc/teumteum/server/domain/teum/entity/Graphic.java
Labels: 🔨 Refactor

#186 Feat : 알림 전송 로직 구현
  src/main/java/umc/teumteum/server/domain/friend/service/FriendServiceImpl.java
  src/main/java/umc/teumteum/server/domain/notification/entity/enums/NotificationType.java
  src/main/java/umc/teumteum/server/domain/notification/service/NotificationOrchestrator.java
  src/main/java/umc/teumteum/server/domain/notification/service/NotificationUseCases.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: ✨ Feature

#192 Fix: 종료시간이 00:00인 TeumRequest 충돌 검사 보정
  src/main/java/umc/teumteum/server/global/validator/ConflictValidator.java
Labels: 🐞 BugFix

#207 Fix : 투두리스트 조회 약속된 틈 조회
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: 🐞 BugFix

#204 Refactor : 사용하지 않는 Import문 & JdbcRepository 어노테이션 정리
  src/main/java/umc/teumteum/server/domain/auth/service/AuthServiceImpl.java
  src/main/java/umc/teumteum/server/domain/auth/service/KakaoOAuthServiceImpl.java
  src/main/java/umc/teumteum/server/domain/auth/service/NaverOAuthServiceImpl.java
  src/main/java/umc/teumteum/server/domain/fcm/dto/FcmTokenRequestDto.java
  src/main/java/umc/teumteum/server/domain/home/ai/generator/AiWishGenerator.java
  src/main/java/umc/teumteum/server/domain/home/converter/WishConverter.java
  src/main/java/umc/teumteum/server/domain/home/dto/response/ActivityResponseDto.java
  src/main/java/umc/teumteum/server/domain/home/exception/status/HomeSuccessStatus.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleJdbcRepository.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleReminderJdbcRepository.java
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/notification/service/NotificationUseCases.java
  src/main/java/umc/teumteum/server/domain/teum/dto/common/TimeSlot.java
  src/main/java/umc/teumteum/server/domain/teum/repository/TeumRequestRepository.java
  src/main/java/umc/teumteum/server/domain/user/dto/UserResponseDTO.java
  src/main/java/umc/teumteum/server/domain/user/repository/RemindAlarmJdbcRepository.java
  src/main/java/umc/teumteum/server/domain/user/repository/RoutineJdbcRepository.java
  src/main/java/umc/teumteum/server/domain/user/repository/UserRepository.java
  src/main/java/umc/teumteum/server/global/apiPayload/ApiResponse.java
  src/main/java/umc/teumteum/server/global/config/FirebaseConfig.java
  src/main/java/umc/teumteum/server/global/config/SecurityConfig.java
  src/main/java/umc/teumteum/server/global/config/WebConfig.java
  src/main/java/umc/teumteum/server/global/jwt/JwtAuthenticationFilter.java
  src/main/java/umc/teumteum/server/global/jwt/JwtProvider.java
  src/main/java/umc/teumteum/server/global/monitoring/controller/InfraTestController.java
  src/main/java/umc/teumteum/server/global/resolver/CurrentUserArgumentResolver.java
  src/main/java/umc/teumteum/server/global/scheduler/DailyTodoReminerScheduler.java
  src/main/java/umc/teumteum/server/global/scheduler/TeumRequestStatusScheduler.java
  src/main/java/umc/teumteum/server/global/validator/ConflictValidator.java
Labels: 🔨 Refactor

#210 Fix : 투두 위시 관련 유효성 검사
  src/main/java/umc/teumteum/server/domain/home/service/HomeServiceImpl.java
Labels: 🐞 BugFix

#218 Refactor : ai 컨텐츠 투두 등록 api에 시간 유효성 검사 추가
  src/main/java/umc/teumteum/server/domain/home/service/ActivityServiceImpl.java
Labels: 🔨 Refactor

#225 Refactor : gpt 프롬프트 수정
  src/main/java/umc/teumteum/server/domain/home/ai/generator/AiWishGenerator.java
Labels: 🔨 Refactor

#227 Fix: COMPLETED 포함하도록 조회 로직 수정
  src/main/java/umc/teumteum/server/domain/home/repository/ScheduleRepository.java
  src/main/java/umc/teumteum/server/domain/teum/service/TeumServiceImpl.java
Labels: 🐞 BugFix
